//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLichHen
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string EmailCus { get; set; }
        public string SDT { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public Nullable<System.TimeSpan> GioHen { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
