//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int ID { get; set; }
        public string CCCD { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<decimal> TienDien { get; set; }
        public Nullable<decimal> TienNuoc { get; set; }
        public Nullable<decimal> TienWifi { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
